# Generated by Django 5.2.8 on 2025-12-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fotografias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(upload_to='fotos/')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
