# Generated by Django 5.2.8 on 2025-12-13 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografias_publicada_alter_fotografias_categoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fotografias',
            new_name='Fotografia',
        ),
    ]
