# Generated by Django 5.2.8 on 2025-12-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografias_categoria_fotografias_legenda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografias',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fotografias',
            name='categoria',
            field=models.CharField(blank=True, choices=[('NEBULOSA', 'Nebulosa'), ('ESTRELA', 'Estrela'), ('GALÁXIA', 'Galáxia'), ('PLANETA', 'Planeta')], max_length=100, null=True),
        ),
    ]
